### ISSUE TITLE
standardize_X issue in model.py

### ISSUE THREAD

**Issue by ewijaya** [wuaalb/keras_extensions#10]
Hi, 

This is a great package. However, I found it breaks on the example with the following message. 

```
$ python examples/dbn_example.py
Using Theano backend.
Traceback (most recent call last):
  File "examples/dbn_example.py", line 14, in <module>
    from keras_extensions.dbn import DBN
  File "//anaconda/lib/python2.7/site-packages/keras_extensions-0.1-py2.7.egg/keras_extensions/dbn.py", line 13, in <module>
  File "//anaconda/lib/python2.7/site-packages/keras_extensions-0.1-py2.7.egg/keras_extensions/models.py", line 1, in <module>
```

I'm using this keras version:

```
In [4]: keras.__version__
Out[4]: '1.0.2'

```
Best,
E.W.

**Comment by wuaalb** [comment]
Hi,

Thanks for reporting.

Keras quite frequently breaks backwards compatibility; which is OK, but this package tends to break because it contains some classes which are modified copies of Keras classes.

I don't use Keras myself currently; so I'm not very motivated to keep this package up-to-date at all times.

I recommend you either use an older version of Keras (don't know exactly which, but pre-1.0 for sure; check date of last commit). Or try to fix the issue yourself (and submit a PR :) ). If you look at the code that generates the error there should be a comment referencing some Keras class which you can have a look at.

**Comment by Wirttplb** [comment]
Hi !
After I encountered the same issue with standardize_X, I have successfully run dbn_example.py with keras 0.3.0. This may be some helpful information, even if it comes late.

**Comment by miaohang123** [comment]
Hi !
  I try to run the example but it breaked on No.82 line: train_model.fit(X_train, batch_size, nb_epoch, verbose=1, shuffle=False, [callbacks=callbacks)]. And the error is as followed:
  TypeError: ('Bad input argument to theano function with name "D:\\PYTHON27\\lib\\site-packages\\keras\\backend\\theano_backend.py:915"  at index 0(0-based)', 'Wrong number of dimensions: expected 2, got 1 with shape (100L,).')
  Best,
  H.M

**Comment by koteswarareddy2017** [comment]
Hi, 

I try to installed keras 0.3.0, but shows in cmd for keras.__version__  as 0.2.0. Moreover tried with 0.3.1 version it shows following error as 'ImportError: cannot import name downsample'. 

while i do this above process, unistalled all keras version packages.

Thanking you in advance...

Regards,
Koteswar

**Comment by akshaytrivedi** [comment]
May be its too late, but it could help someone in future. This works with keras 0.20 or 0.30 with theano 0.8.0. In later versions of theano you get 'cannot import name downsample' as downsample module is moved.

**Comment by Noah-Yasarturk** [comment]
Still having issues importing standardize_X after installing keras 0.2.0 and theano 0.8.0. 
@miaohang123 it looks like you're using python 2.7 (your native system python) maybe try with Python 3 with a virtual envt?

Should I solve this issue, I'll report what I did shortly.
